title: Hello, I'm Jing
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/jing-long" # the subpath of your site, e.g. /blog
url: "https://jing042323.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jing Long # add your name
author-img: jinglong2.jpg # add your photo
about-author: I am a curious data enthusiast with a background in Economics and Business Analytics. Always hungry to keep learning. # add description
social-twitter: Jing Long # add your Twitter handle
social-facebook: Jing Long # add your Facebook handle
social-github: jing042323 # add your Github handle
social-linkedin: Jing Long # add your Linkedin handle
social-email: jing042323@163.com # add your Email address

# Disqus
discus-identifier: jing long # add your discus identifier

# Tracker
analytics: UA-192087562-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
